# -*- coding: utf-8 -*-
"""Concatenate csv files.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yOEt2Jgmp6wicK07OnNcVXXiZLH6zpEI
"""

#read data files and concatenate them into one csv file.
import pandas as pd

train=pd.read_table('train.txt', delimiter = ';', header=None)
val=pd.read_table('val.txt', delimiter = ';', header=None )
test=pd.read_table('test.txt', delimiter = ';', header=None)
data = pd.concat([train ,  val ])
data.reset_index(drop=True, inplace=True)
data.columns = ["text", "label"]
data.to_csv('data.csv')
test.reset_index(drop=True, inplace=True)
test.columns = ["text", "label"]
test.to_csv('test.csv')